version: "3"
services:
  backend:
    environment:
      - LOCATION_HOST=localhost:3333
      - LOCATION_MODE=local
    build:
      context: ./backend
      dockerfile: Dockerfile_backend
    volumes:
      - "./backend:/src/app"
    ports:
      - "3333:3333"
  frontend:
    volumes:
      - './frontend/public:/frontend/public'
      - './frontend/src:/frontend/src'
    build:
      context: ./frontend
      dockerfile: Dockerfile_frontend
    ports:
      - "8080:8080"
