version: "3"
services:
  backend:
    environment:
      - LOCATION_HOST_FRONTEND=https://dev.bullfinch.tigermilk.ru
      - LOCATION_HOST_BACKEND=https://dev.bullfinch.tigermilk.ru/api
      - MONGO_LOGIN=asfoASfg35gse
      - MONGO_PASSWORD=sdogo235DSgbseGazb21
      - LOCATION_MODE=production
    build:
      context: ./backend
      dockerfile: Dockerfile_backend_prod
    volumes:
      - "./backend:/src/app"
    links:
      - mongo
    ports:
      - "3333:3333"
  nginx:
    build:
      context: .
      dockerfile: dockerfile_nginx
    ports:
      - "8080:80"
    links:
      - backend
    restart: always
  mongo:
    build:
      context: .
      dockerfile: dockerfile_mongo
    volumes:
      - './data:/data/db'
      - './mongodb/logs:/var/log/mongodb'
    ports:
      - "27017:27017"
    restart: always
