FROM node:12.16.0

RUN mkdir /src
RUN mkdir /src/app
WORKDIR /src
COPY package.json /src
RUN npm install
RUN npm install -g nodemon
RUN npm install -g pm2
WORKDIR /src/app
CMD pm2 start app.js --no-daemon
